name: Daily Haiku to Teams and SMS

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 8AM UTC (7/8 AM EST depending on DST)
  workflow_dispatch:

jobs:
  post-daily-haiku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Try to generate haiku (first attempt)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_poem.py || { echo "❌ Haiku generation failed. Will retry later."; exit 99; }

      - name: Retry after 30 minutes if haiku failed
        if: ${{ failure() }}
        timeout-minutes: 31
        run: |
          echo "⏳ Waiting 30 minutes before retry..."
          sleep 1800
          python generate_poem.py || exit 1

      - name: Fail if haiku file is still missing
        run: |
          if [ ! -s poem.txt ]; then
            echo "❌ Haiku file is missing or empty after retry. Aborting post."
            exit 1
          fi

      - name: Debug – list directory contents
        run: ls -lh

      - name: Ensure jq is installed
        run: |
          if ! command -v jq >/dev/null; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

      - name: Convert haiku to JSON for Teams
        run: |
          awk '
            BEGIN {
              print "["
              count = 0
            }
            {
              gsub(/"/, "\\\"")
              lines[count++] = $0
            }
            END {
              for (i = 0; i < count; i++) {
                if (lines[i] != "") {
                  sep = (i > 0 && lines[i-1] == "") ? ", \"separator\": true, \"spacing\": \"Medium\"" : ""
                  print "  {\"type\": \"TextBlock\", \"text\": \"" lines[i] "\", \"wrap\": true" sep "}" (i < count - 1 ? "," : "")
                }
              }
              print "]"
            }
          ' poem.txt > poem_blocks.json

      - name: Post haiku to Teams channels
        env:
          TEAMS_WEBHOOK_RANDOM: ${{ secrets.TEAMS_WEBHOOK_RANDOM }}
          # Add more as needed:
          # TEAMS_WEBHOOK_SOMETHING_ELSE: ${{ secrets.TEAMS_WEBHOOK_SOMETHING_ELSE }}
        run: |
          for VAR in $(env | grep '^TEAMS_WEBHOOK_' | cut -d= -f1); do
            WEBHOOK_URL="${!VAR}"
            echo "🔗 Posting to $VAR..."

            JSON_PAYLOAD=$(jq -n --slurpfile body poem_blocks.json '
              {
                attachments: [
                  {
                    contentType: "application/vnd.microsoft.card.adaptive",
                    content: {
                      "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
                      type: "AdaptiveCard",
                      version: "1.0",
                      body: (
                        [
                          {
                            "type": "TextBlock",
                            "size": "Large",
                            "weight": "Bolder",
                            "text": "📜 Daily Haiku",
                            "horizontalAlignment": "Center"
                          }
                        ] + $body[0]
                      )
                    }
                  }
                ]
              }')

            curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$WEBHOOK_URL"
            echo "✅ Posted to $VAR"
          done

      - name: Validate and clean SMS recipient list
        id: validate_sms
        run: |
          echo "🔎 Checking SMS recipient list..."
          if [ -z "${{ vars.SMS_RECIPIENTS }}" ]; then
            echo "❌ SMS_RECIPIENTS is empty. Aborting."
            exit 1
          fi

          # Remove spaces after commas automatically
          CLEANED=$(echo "${{ vars.SMS_RECIPIENTS }}" | sed 's/, */,/g')

          # Basic validation: check that every entry contains "@"
          IFS=',' read -ra ADDRS <<< "$CLEANED"
          for addr in "${ADDRS[@]}"; do
            if [[ "$addr" != *@* ]]; then
              echo "❌ Invalid address format: $addr"
              exit 1
            fi
          done

          echo "✅ SMS recipients look valid."

          # Save cleaned list for the next step
          echo "recipients=$CLEANED" >> $GITHUB_OUTPUT

      - name: Send Daily Haiku SMS via Outlook
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.OUTLOOK_USERNAME }}
          password: ${{ secrets.OUTLOOK_APP_PASSWORD }}
          subject: "[Daily Haiku]"
          body: |
            $(cat poem.txt)
          to: ${{ steps.validate_sms.outputs.recipients }}
          from: "haikubot@outlook.com"
          secure: false
