name: Daily Poem to Teams

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 8AM UTC (7/8 AM EST depending on DST)
  workflow_dispatch:

jobs:
  post-daily-poem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Try to generate poem (1st attempt)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_poem.py || { echo "❌ Poem generation failed. Will retry later."; exit 99; }

      - name: Retry after 30 minutes if poem failed
        if: ${{ failure() }}
        timeout-minutes: 31
        run: |
          echo "⏳ Waiting 30 minutes before retry..."
          sleep 1800
          python generate_poem.py || exit 1  # fail hard if still bad

      - name: Fail if poem file is still missing
        run: |
          if [ ! -s poem.txt ]; then
            echo "❌ Poem file is missing or empty after retry. Aborting post."
            exit 1
          fi

      - name: Post poem to Teams channels
        env:
          # To add another channel posting, add: TEAMS_WEBHOOK_CHANNEL_NAME: ${{ secrets.TEAMS_WEBHOOK_CHANNEL_NAME }}
          TEAMS_WEBHOOK_RANDOM: ${{ secrets.TEAMS_WEBHOOK_RANDOM }}
        run: |
          # Convert newlines + blank lines to <br><br> formatting for Teams
          POEM=$(sed 's/$/<br>/' poem.txt | paste -sd '' - | jq -Rs .)

          for VAR in $(env | grep '^TEAMS_WEBHOOK_' | cut -d= -f1); do
            WEBHOOK_URL="${!VAR}"
            echo "🔗 Posting to $VAR..."

            JSON_PAYLOAD=$(jq -n --arg poem "$POEM" '
              {
                attachments: [
                  {
                    contentType: "application/vnd.microsoft.card.adaptive",
                    content: {
                      "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
                      type: "AdaptiveCard",
                      version: "1.0",
                      body: [
                        {
                          type: "TextBlock",
                          size: "Large",
                          weight: "Bolder",
                          text: "📜 Daily Poem",
                          horizontalAlignment: "Center"
                        },
                        {
                          type: "TextBlock",
                          text: $poem,
                          wrap: true,
                          separator: true
                        }
                      ]
                    }
                  }
                ]
              }')

            curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$WEBHOOK_URL"
            echo " ✅ Posted to $VAR"
          done
