name: Daily Poem to Teams

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 8AM UTC (7/8 AM EST depending on DST)
  workflow_dispatch:

jobs:
  post-daily-poem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Try to generate poem (1st attempt)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_poem.py || { echo "❌ Poem generation failed. Will retry later."; exit 99; }

      - name: Retry after 30 minutes if poem failed
        if: ${{ failure() }}
        timeout-minutes: 31
        run: |
          echo "⏳ Waiting 30 minutes before retry..."
          sleep 1800
          python generate_poem.py || exit 1

      - name: Fail if poem file is still missing
        run: |
          if [ ! -s poem.txt ]; then
            echo "❌ Poem file is missing or empty after retry. Aborting post."
            exit 1
          fi

      - name: Post poem to Teams channels
        env:
          TEAMS_WEBHOOK_RANDOM: ${{ secrets.TEAMS_WEBHOOK_RANDOM }}
          # Add more as needed:
          # TEAMS_WEBHOOK_SOMETHING_ELSE: ${{ secrets.TEAMS_WEBHOOK_SOMETHING_ELSE }}
        run: |
          # Convert each line of the poem into a separate TextBlock
          POEM_BODY=$(awk 'BEGIN { print "[" }
            NF { gsub(/"/, "\\\""); print "{\"type\": \"TextBlock\", \"text\": \"" $0 "\", \"wrap\": true}," }
            !NF { print "{\"type\": \"TextBlock\", \"text\": \"\", \"wrap\": true}," }
            END { print "]" }' poem.txt)

          for VAR in $(env | grep '^TEAMS_WEBHOOK_' | cut -d= -f1); do
            WEBHOOK_URL="${!VAR}"
            echo "🔗 Posting to $VAR..."

            JSON_PAYLOAD=$(jq -n --argjson body "$POEM_BODY" '
              {
                attachments: [
                  {
                    contentType: "application/vnd.microsoft.card.adaptive",
                    content: {
                      "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
                      type: "AdaptiveCard",
                      version: "1.0",
                      body: (
                        [
                          {
                            "type": "TextBlock",
                            "size": "Large",
                            "weight": "Bolder",
                            "text": "📜 Daily Poem",
                            "horizontalAlignment": "Center"
                          }
                        ] + $body
                      )
                    }
                  }
                ]
              }')

            curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$WEBHOOK_URL"
            echo " ✅ Posted to $VAR"
          done
